trigger:
    - main

pool:
    vmImage: "ubuntu-latest"

steps:
    - script: |
          npm install
          npm run build
      displayName: "Build the React App"

    - task: PublishBuildArtifacts@1
      inputs:
          pathtoPublish: "build"
          artifactName: "drop"
      displayName: "Publish Artifact"
